routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::get('rooms_direction/{location}/directions', 'RoomController@directions')->name('rooms.direction');

Route::get('/lang/{local}', 'HomeController@changeLocal')->name('lang');

Route::post('rooms/{room}/reservations', 'RoomController@reservations')->name('rooms.reservations');

Route::group(['middleware' => ['language']], function () {
    Auth::routes();

    Route::get('/authorize', 'AuthController@index');

    Route::get('/i/{code}', 'VisitController@visitCode')->name('visit.code');

    Route::get('/rates/{code}', 'VisitController@rateUs')->name('visit.rates');
    Route::post('/rates/{code}', 'VisitController@storeRate')->name('visits.storeRate');

    Route::get('rooms/{id}/visit', 'RoomController@visit')->name('rooms.visit');
    Route::group(['middleware' => ['auth', 'language', 'permission']], function () {

        Route::get('/', 'HomeController@index')->name('home');

        Route::get('/visits', 'VisitController@index')->name('visits.index');
        Route::get('/visits/create', 'VisitController@create')->name('visits.create');
        Route::post('/visits/store', 'VisitController@store')->name('visits.store');
        Route::get('/visits/{visitor_id}/check_in', 'VisitController@checkIn')->name('visits.checkIn');
        Route::get('/visits/{visitor_id}/check_out', 'VisitController@checkOut')->name('visits.checkOut');
        Route::get('/visits/init', 'VisitController@init')->name('visits.init');
        Route::get('/visits/init/{id}/accepted', 'VisitController@accepted')->name('visits.accepted');
        Route::post('/visits/init/{id}/decline', 'VisitController@decline')->name('visits.decline');
        Route::delete('/visits/{visit}','VisitController@cancel')->name('visits.cancel');
        Route::get('/visits/{visit}/notes', 'VisitController@createNote')->name('visits.createNote');
        Route::put('/visits/{visit}/notes', 'VisitController@storeNote')->name('visits.storeNote');




        Route::resource('rooms', 'RoomController');

        Route::get('setting', 'SettingController@edit')->name('setting.edit');
        Route::put('setting', 'SettingController@update')->name('setting.update');
        Route::get('setting/{id}','SettingController@delete')->name('setting.logo.delete');

        Route::resource('users', 'UserController')->except('show');

//        Route::resource('departments', 'DepartmentController')->except('show');

        Route::get('/reports', 'ReportController@index')->name('reports.index');
        Route::get('/reports/meetings/export', 'ReportController@meetingsExport')->name('reports.meetings.export');
        Route::get('/reports/visitors/export', 'ReportController@visitorsExport')->name('reports.visitors.export');
        Route::get('/reports/users/export', 'ReportController@usersExport')->name('reports.users.export');
        Route::get('/reports/rates/export', 'ReportController@ratesExport')->name('reports.rates.export');


    });

});

app/User.php
<?php

namespace App;

use App\Service\Permissions\Permissions;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
        'type',
        'language'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


    /**
     * @param $route
     *
     * @return bool
     */
    public function canDo($route)
    {
        return Permissions::candDO($this->role, $route);
    }

    public function IsAdmin()
    {
        return $this->role == 'admin';
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateUser;
use App\Http\Requests\UpdateUser;
use App\User;

class UserController extends Controller
{

    public function index()
    {
        return view('users.index', [
            'users' => User::paginate(15),
        ]);
    }

    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateUser $request
     */
    public function store(CreateUser $request)
    {
        User::create([
            'name'     => $request->get('name'),
            'email'    => $request->get('email'),
            'role'     => $request->get('role'),
            'language' => $request->get('language'),
            'password' => bcrypt($request->get('password')),
        ]);

        return redirect('users')
            ->with('success', trans('messages.added_successfully'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param User $user
     * @internal param int $id
     */
    public function edit(User $user)
    {
        if ($user->id != auth()->user()->id && !$user->IsAdmin()) {
            abort(404);
        }

        return view('users.edit', [
            'user' => $user,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateUser $request
     * @param User $user
     * @internal param int $id
     */
    public function update(UpdateUser $request, User $user)
    {
        if ($user->id != auth()->user()->id && !$user->IsAdmin()) {
            abort(404);
        }

        $data = [
            'name'     => $request->get('name'),
            'language' => $request->get('language'),
        ];

        if ($request->has('password') && $request->get('password') != null) {
            $data['password'] = bcrypt($request->get('password'));
        }

        if ($user->IsAdmin() && $request->has('email', 'role')) {
            $data['email'] = $request->get('email');
            $data['role']  = $request->get('role');
        }

        $user->update($data);

        return redirect(route('users.index'))
            ->with('success', trans('messages.updated_successfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::destroy($id);

        return redirect(route('users.index'))
            ->with('success', trans('messages.deleted_successfully'));
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-md-8 col-md-offset-2">
        <div class="box">
            <div class="panel-body">
                <h3>@lang('validation.attributes.add_new_user')</h3>
                <br>
                <form method="post" action="{{ route('users.store')}}">
                    {{csrf_field()}}
                    <div class="form-group">
                        <label class="col-md-4">@lang('validation.attributes.name')</label>
                        <div class="col-md-8">
                            <input type="text" name="name" value="{{ old('name') }}" class="form-control" required
                                   autofocus/>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4">@lang('validation.attributes.password')</label>
                        <div class="col-md-8">
                            <input type="password" name="password" class="form-control" required
                                   autofocus/>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4">@lang('validation.attributes.email')</label>
                        <div class="col-md-8">
                            <input type="text" value="{{ old('email') }}" name="email" class="form-control" autofocus/>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4">@lang('validation.attributes.role')</label>
                        <div class="col-md-8">
                            <select name="role" class="form-control" required autofocus>
                                <option value="">@lang('validation.attributes.please_select')</option>
                                <option value="user"
                                        @if(old('role') =='admin') selected @endif>@lang('validation.attributes.standard_user')</option>
                                <option value="reception"
                                        @if(old('role') =='reception') selected @endif>@lang('validation.attributes.reception_user')</option>
                                <option value="admin"
                                        @if(old('role') =='admin') selected @endif>@lang('validation.attributes.admin_user')</option>
                            </select>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4">@lang('validation.attributes.language')</label>
                        <div class="col-md-8">
                            <select name="language" class="form-control" required autofocus>
                                <option value="">@lang('validation.attributes.please_select')</option>
                                <option value="ar" @if(old('language') == "ar") selected @endif>@lang('validation.attributes.ar')</option>
                                <option value="en" @if(old('language') == "en") selected @endif>@lang('validation.attributes.en')</option>
                            </select>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="@lang('validation.attributes.add')"
                               class="btn visitors-theme-button saveBtn pull-left"/>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-md-8 col-md-offset-2">
        <div class="box">
            <div class="panel-body">
                <h3>@lang('validation.attributes.edit_user')</h3>
                <br>
                <form method="post" action="{{ route('users.update', $user->id) }}">
                    {{csrf_field()}}
                    <input type="hidden" name="_method" value="put"/>
                    <div class="form-group">
                        <label class="col-md-4">@lang('validation.attributes.name')</label>
                        <div class="col-md-8"><input value="{{$user->name}}" type="text" name="name"
                                                     class="form-control" required autofocus/></div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4">@lang('validation.attributes.password')</label>
                        <div class="col-md-8">
                            <input type="password" name="password" class="form-control"
                                   autofocus/>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4">@lang('validation.attributes.email')</label>
                        <div class="col-md-8"><input value="{{$user->email}}" type="email" name="email"
                                                     class="form-control" @if($user->role != "admin") readonly @endif/></div>
                        <div class="clearfix"></div>
                    </div>
                    @if(auth()->user()->role == "admin")
                        <div class="form-group">
                            <label class="col-md-4">@lang('validation.attributes.role')</label>
                            <div class="col-md-8">
                                <select name="role" class="form-control" required autofocus>
                                    <option value="user"
                                            @if(old('role', $user->role) =='admin') selected @endif>@lang('validation.attributes.standard_user')</option>
                                    <option value="reception"
                                            @if(old('role', $user->role) =='reception') selected @endif>@lang('validation.attributes.reception_user')</option>
                                    <option value="admin"
                                            @if(old('role', $user->role) =='admin') selected @endif>@lang('validation.attributes.admin_user')</option>
                                </select>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    @endif
                    <div class="form-group">
                        <label class="col-md-4">@lang('validation.attributes.language')</label>
                        <div class="col-md-8">
                            <select name="language" class="form-control" required autofocus>
                                <option value="">@lang('validation.attributes.please_select')</option>
                                <option value="ar" @if(old('language', $user->language) == "ar") selected @endif>@lang('validation.attributes.ar')</option>
                                <option value="en" @if(old('language', $user->language) == "en") selected @endif>@lang('validation.attributes.en')</option>
                            </select>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="@lang('validation.attributes.save')"
                               class="btn visitors-theme-button saveBtn pull-left"/>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row page-title">
        <div class="col-md-12">

            <div class="col-md-6" style="text-align: left;">

            </div>
        </div>
        <div class="col-md-8 col-xs-8"><h3>@lang('validation.attributes.users')</h3></div>
        <div class="col-md-4 col-xs-4"><a class="visitors-theme-button" id="newUserBtn" href="/users/create"><i
                        class="fas fa-plus"></i>@lang('validation.attributes.add')</a></div>
    </div>

    <div class="box" id="usersContainer">
        <table class="table users-table" id="usersListTable">
            <thead>
            <tr>
            <th style="text-align: center">@lang('validation.attributes.name')</th>
            <th style="text-align: center">@lang('validation.attributes.email')</th>
            <th style="text-align: center">@lang('validation.attributes.role')</th>
            <th style="text-align: center">@lang('validation.attributes.language')</th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach($users as $user)

                <tr>
                    <td style="text-align: center">{{$user->name}}</td>
                    <td style="text-align: center">{{$user->email}}</td>
                    <td style="text-align: center">@lang('validation.attributes.'.$user->role)</td>
                    <td style="text-align: center">@lang('validation.attributes.' . $user->language)</td>
                    <td class="text-left">
                        <a class="btn btn-sm" href="/users/{{$user->id}}/edit">@lang('validation.attributes.edit')</a>
                        <button class="btn btn-sm btn-danger btn-delete" data-toggle="modal"
                                data-target="#delete-modal-{{$user->id}}">@lang('validation.attributes.delete')</button>
                        <form method="post" action="/users/{{$user->id}}">
                            <input type="hidden" name="_method" value="delete"/>
                            {{ csrf_field() }}
                            <input type="hidden" name="id" value="{{$user->id}}"/>

                            <!-- Modal HTML -->
                            <div id="delete-modal-{{$user->id}}" class="modal fade">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title">@lang('messages.delete_confirmation')</h4>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default"
                                                    data-dismiss="modal">@lang('validation.attributes.no')</button>
                                            <button type="button" class="btn btn-primary"
                                                    onclick="$(this).closest('form').submit();">@lang('validation.attributes.yes')</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    <div style="text-align: center">
        {{ $users->appends(Request::except('page'))->links() }}
    </div>
@endsection
@section('js')
    <script>
        $("#usersListTable").DataTable({
            language: {
                search: "@lang('validation.attributes.search')",
                Show: "@lang('validation.attributes.show')",
                entries: "@lang('validation.attributes.entries')",
                info: "@lang('validation.attributes.show') _END_ @lang('validation.attributes.out_of') _TOTAL_",
                lengthMenu: "@lang('validation.attributes.show') _MENU_ @lang('validation.attributes.entries')",
                paginate: {
                    next: "@lang('validation.attributes.next')",
                    previous: "@lang('validation.attributes.previous')"
                }
            }
        });
    </script>
@endsection