routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::get('rooms_direction/{location}/directions', 'RoomController@directions')->name('rooms.direction');

Route::get('/lang/{local}', 'HomeController@changeLocal')->name('lang');

Route::post('rooms/{room}/reservations', 'RoomController@reservations')->name('rooms.reservations');

Route::group(['middleware' => ['language']], function () {
    Auth::routes();

    Route::get('/authorize', 'AuthController@index');

    Route::get('/i/{code}', 'VisitController@visitCode')->name('visit.code');

    Route::get('/rates/{code}', 'VisitController@rateUs')->name('visit.rates');
    Route::post('/rates/{code}', 'VisitController@storeRate')->name('visits.storeRate');

    Route::get('rooms/{id}/visit', 'RoomController@visit')->name('rooms.visit');
    Route::group(['middleware' => ['auth', 'language', 'permission']], function () {

        Route::get('/', 'HomeController@index')->name('home');

        Route::get('/visits', 'VisitController@index')->name('visits.index');
        Route::get('/visits/create', 'VisitController@create')->name('visits.create');
        Route::post('/visits/store', 'VisitController@store')->name('visits.store');
        Route::get('/visits/{visitor_id}/check_in', 'VisitController@checkIn')->name('visits.checkIn');
        Route::get('/visits/{visitor_id}/check_out', 'VisitController@checkOut')->name('visits.checkOut');
        Route::get('/visits/init', 'VisitController@init')->name('visits.init');
        Route::get('/visits/init/{id}/accepted', 'VisitController@accepted')->name('visits.accepted');
        Route::post('/visits/init/{id}/decline', 'VisitController@decline')->name('visits.decline');
        Route::delete('/visits/{visit}','VisitController@cancel')->name('visits.cancel');
        Route::get('/visits/{visit}/notes', 'VisitController@createNote')->name('visits.createNote');
        Route::put('/visits/{visit}/notes', 'VisitController@storeNote')->name('visits.storeNote');




        Route::resource('rooms', 'RoomController');

        Route::get('setting', 'SettingController@edit')->name('setting.edit');
        Route::put('setting', 'SettingController@update')->name('setting.update');
        Route::get('setting/{id}','SettingController@delete')->name('setting.logo.delete');

        Route::resource('users', 'UserController')->except('show');

//        Route::resource('departments', 'DepartmentController')->except('show');

        Route::get('/reports', 'ReportController@index')->name('reports.index');
        Route::get('/reports/meetings/export', 'ReportController@meetingsExport')->name('reports.meetings.export');
        Route::get('/reports/visitors/export', 'ReportController@visitorsExport')->name('reports.visitors.export');
        Route::get('/reports/users/export', 'ReportController@usersExport')->name('reports.users.export');
        Route::get('/reports/rates/export', 'ReportController@ratesExport')->name('reports.rates.export');


    });

});

app/Room.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Room extends Model
{
    protected $table = 'rooms';

    protected $fillable = [
        'name_ar',
        'name_en',
        'size',
        'approval',
        'location',
        'floor',
        'direction',
    ];


    public function visits()
    {
        return $this->hasMany(Visit::class, 'room_id');
    }

    public function current_meeting()
    {
        return $this->visits()
            ->whereTime('time_start', '<=', Carbon::now()->toTimeString())
            ->whereTime('time_end', '>=', Carbon::now()->toTimeString())
            ->whereDate('date', date('Y-m-d'))
            ->orderBy('time_start','asc')
            ->whereIn('status', [
                'ready',
                'accepted',
            ])->first();
    }
}

app/Http/Controllers/RoomController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateRoom;
use App\Room;
use App\Setting;
use Carbon\Carbon;
use Illuminate\Http\Request;

class RoomController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('rooms.index', [
            'rooms' => Room::all(),
        ]);
    }


    /**
     * return view for new room
     *
     */

    public function create()
    {
        $rooms_count = Room::count();
        $rooms_limit = Setting::latest()->first()->rooms_limits;

        if ($rooms_count >= $rooms_limit) {
            return redirect(route('rooms.index'))
                ->with('danger', trans('messages.rooms_limits'));
        }
        return view('rooms.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateRoom $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRoom $request)
    {
        Room::create([
            'name_ar' => $request->get('name_ar'),
            'name_en' => $request->get('name_en'),
            'size' => $request->get('size'),
            'floor' => $request->get('floor'),
            'approval' => $request->get('approval'),
            'location' => $request->get('location'),
            'direction' => $request->get('direction'),
        ]);

        return redirect(route('rooms.index'))
            ->with('success', trans('messages.added_successfully'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('rooms.edit', [
            'room' => Room::findOrFail($id),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param CreateRoom $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(CreateRoom $request, $id)
    {
        $room = Room::findOrFail($id);

        $room->update([
            'name_ar' => $request->get('name_ar'),
            'name_en' => $request->get('name_en'),
            'size' => $request->get('size'),
            'approval' => $request->get('approval'),
            'floor' => $request->get('floor'),
            'location' => $request->get('location'),
            'direction' => $request->get('direction'),
        ]);

        return redirect(route('rooms.index'))
            ->with('success', trans('messages.updated_successfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Room::destroy($id);

        return redirect(route('rooms.index'))
            ->with('success', trans('messages.deleted_successfully'));
    }

    public function visit($id)
    {
        $room = Room::with([
            'visits' => function ($query) {
                $query->whereIn('status', [
                    'ready',
                    'accepted',
                ]);
                $query->whereDate('date', date('Y-m-d'));
                $query->orderby('time_start', 'asc');
            },
        ])->findOrFail($id);

        return view('rooms.visits', [
            'room' => $room,
            'settings' => Setting::latest()->first(),
            'currentMeeting' => $room->current_meeting()
        ]);

    }

    public function directions($location)
    {

        $rooms = Room::where('floor', $location)->take(5)->get();

        if (count($rooms) == 0) {
            abort(404);
        }

        return view('rooms.directions', [
            'rooms' => $rooms,
            'settings' => Setting::latest()->first(),
            'location' => $location,
        ]);
    }

    public function reservations(Request $request, Room $room)
    {
        $visits = $room->visits->where('date', new Carbon($request->get('meeting_date')));

        $visits_subset = $visits->map(function ($visit) {
            return $visit->only(['time_start', 'time_end']);
        });

        return response()->json($visits_subset);
    }
}

resources/views/rooms/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row page-title">
        <div class="col-md-12">
            <h3 class="col-md-6">@lang('validation.attributes.meeting_rooms')</h3>
        </div>
    </div>
    <div class="col-md-8 col-md-offset-2">
        <div class="box">
            <div class="panel-body">
                <form method="post" action="{{ route('rooms.store') }}">
                    {{csrf_field()}}
                    <div class="form-group">
                        <label class="col-md-4">@lang('validation.attributes.name_ar')</label>
                        <div class="col-md-8"><input value="{{ old('name_ar') }}" type="text" name="name_ar"
                                                     class="form-control" required autofocus/></div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4">@lang('validation.attributes.name_en')</label>
                        <div class="col-md-8"><input value="{{ old('name_en') }}" type="text" name="name_en"
                                                     class="form-control" required autofocus/></div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4">@lang('validation.attributes.size')</label>
                        <div class="col-md-8"><input value="{{ old('size') }}" type="number" name="size"
                                                     class="form-control" required autofocus/></div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4">@lang('validation.attributes.request_approval')</label>
                        <div class="col-md-8">
                            <select name="approval" class="form-control" required autofocus>
                                <option value="0" @if(old('approval') == 0) selected @endif>@lang('validation.attributes.approval_not_required')</option>
                                <option value="1" @if(old('approval') == 1) selected @endif>@lang('validation.attributes.approval_required')</option>
                            </select>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="form-group"><label for="location" class="col-md-4">@lang('validation.attributes.location')</label>
                        <div class="col-md-8">
                            <input value="{{ old('location') }}" id="location" type="text" name="location"
                                   class="form-control" placeholder="https://goo.gl/maps/xxxxx" autofocus/>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="form-group"><label for="floor" class="col-md-4">@lang('validation.attributes.floor')</label>
                        <div class="col-md-8">
                            <select name="floor" id="floor" class="form-control" required autofocus>
                                <option value="">@lang('messages.please_choose')</option>
                                @for($i = 1; $i <= 20; $i++)
                                <option value="{{$i}}" @if(old('floor') == $i) selected @endif>@lang('validation.attributes.floor') {{$i}}</option>
                                @endfor
                            </select>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="form-group"><label for="" class="col-md-4">@lang('validation.attributes.direction')</label>
                        <div class="col-md-8">
                            <select name="direction" id="" class="form-control" required autofocus>
                                <option value="left" @if(old('direction') == "left") selected @endif>@lang('validation.attributes.left')</option>
                                <option value="right" @if(old('direction') == "right") selected @endif>@lang('validation.attributes.right')</option>
                            </select></div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="@lang('validation.attributes.save')"
                               class="btn visitors-theme-button saveBtn pull-left"/>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/rooms/directions.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Directions Screen</title>

    <!-- Bootstrap -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/bootstrap-rtl.min.css') }}">
    <link rel="stylesheet" href="{{ asset('fontawesome/css/font-awesome.css') }}">
    <link href="{{ asset('css/direction_screen.css') }}" rel="stylesheet">
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">
            <a class="navbar-brand" href="#">
                @if(isset($settings->logo))
                    <img class="navbar-logo" src="{{ asset('/images/'.$settings->logo)}}"/>
                @else
                    <img class="navbar-logo" src="{{ asset('/images/logo.png')}}"/>
                @endif
            </a>
        </div>
        <div class="col-md-8" id="header-info">
            <h1 class="text-center floor_name">الدور {{$location}}<small><br><p id="currentTime"></p></small></h1>
        </div>
        <div class="col-md-2">
            <a class="navbar-brand" href="#">
                @if(isset($settings->logo))
                    <img class="navbar-logo" src="{{ asset('/images/'.$settings->logo)}}"/>
                @else
                    <img class="navbar-logo" src="{{ asset('/images/logo.png')}}"/>
                @endif
            </a>
        </div>
    </div>
    <div class="vertical-space"></div>
    @foreach($rooms as $room)
        <div class="panel panel-default">
            <div class="panel-body" id="room_name_container">
                <table width="100%" border="0">
                    <tbody><tr>
                        <td align="center">
                            <h1 class="room_name">
                                @if(app()->getLocale() == "ar")
                                    {{$room->name_ar}}
                                @else
                                    {{$room->name_en}}
                                @endif
                                @if($room->current_meeting() != null)
                                    <br>
                                        <small>
                                            {{$room->current_meeting()->title}}
                                        </small>
                                @endif
                            </h1>
                        </td>
                        <td width="140" valign="middle">
                            <i class="fa fa-long-arrow-{{ $room->direction }} arrow-icon"></i></td>
                    </tr>
                    </tbody></table>
            </div>
        </div>
    @endforeach
</div>
<script src="{{ asset('js/app.js') }}"></script>
<script>
    setInterval(function(){
        var date = new Date();
        $("#currentTime").html(
            date.getHours() + ":" + (date.getMinutes()<10?'0':'') + date.getMinutes() + ":" + (date.getSeconds()<10?'0':'') + date.getSeconds()
        );
    }, 1000)
    setInterval(function(){
        if(navigator.onLine){
            window.location.reload(true);
        }
    }, 60000)
</script>
</body>
</html>

resources/views/rooms/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row page-title">
        <div class="col-md-12">
            <h3 class="col-md-6">@lang('validation.attributes.meeting_rooms')</h3>
        </div>
    </div>
    <div class="col-md-8 col-md-offset-2">
        <div class="box">
            <div class="panel-body">
                <form method="post" action="{{ route('rooms.update', $room->id) }}">
                    {{ method_field('PATCH') }}
                    {{csrf_field()}}
                    <div class="form-group">
                        <label class="col-md-4">@lang('validation.attributes.name_ar')</label>
                        <div class="col-md-8"><input value="{{ old('name_ar' , $room->name_ar) }}" type="text" name="name_ar"
                                                     class="form-control" required autofocus/></div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4">@lang('validation.attributes.name_en')</label>
                        <div class="col-md-8"><input value="{{ old('name_en', $room->name_en) }}" type="text" name="name_en"
                                                     class="form-control" required autofocus/></div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4">@lang('validation.attributes.size')</label>
                        <div class="col-md-8"><input value="{{ old('size', $room->size) }}" type="number" name="size"
                                                     class="form-control" required autofocus/></div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4">@lang('validation.attributes.request_approval')</label>
                        <div class="col-md-8">
                            <select name="approval" class="form-control" required autofocus>
                                <option value="0" @if(old('approval') == 0) selected @endif>@lang('validation.attributes.approval_not_required')</option>
                                <option value="1" @if(old('approval') == 1) selected @endif>@lang('validation.attributes.approval_required')</option>
                            </select>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="form-group"><label for="location" class="col-md-4">@lang('validation.attributes.location')</label>
                        <div class="col-md-8">
                            <input value="{{ old('location',$room->location) }}" id="location" type="text" name="location"
                                   class="form-control" placeholder="https://goo.gl/maps/xxxxx" autofocus/>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="form-group"><label for="floor" class="col-md-4">@lang('validation.attributes.floor')</label>
                        <div class="col-md-8">
                            <select name="floor" id="floor" class="form-control" required autofocus>
                                <option value="">@lang('messages.please_choose')</option>
                                @for($i = 1; $i <= 20; $i++)
                                    <option value="{{$i}}" @if(old('floor', $room->floor) == $i) selected @endif>@lang('validation.attributes.floor') {{$i}}</option>
                                @endfor
                            </select>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="form-group"><label for="" class="col-md-4">@lang('validation.attributes.direction')</label>
                        <div class="col-md-8">
                            <select name="direction" id="" class="form-control" required autofocus>
                                <option value="left" @if(old('direction', $room->direction) == "left") selected @endif>@lang('validation.attributes.left')</option>
                                <option value="right" @if(old('direction', $room->direction) == "right") selected @endif>@lang('validation.attributes.right')</option>
                            </select></div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="@lang('validation.attributes.save')"
                               class="btn visitors-theme-button saveBtn pull-left"/>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/rooms/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row page-title">
        <div class="col-md-11 col-xs-8"><h3 class="col-md-6">@lang('validation.attributes.meeting_rooms')</h3></div>
        <div class="col-md-1 col-xs-4"><a href="{{route('rooms.create')}}" class="visitors-theme-button pull-left" id="newRoomBtn">@lang('validation.attributes.add')</a></div>

    </div>
    <div class="box" style="overflow: auto;">
        @if(count($rooms) === 0)
            <div class="no-data">@lang('validation.attributes.no_data')</div>
        @else
            <table class="table">
                <thead>
                <th>@lang('validation.attributes.name_ar')</th>
                <th>@lang('validation.attributes.name_en')</th>
                <th>@lang('validation.attributes.size')</th>
                <th>@lang('validation.attributes.request_approval')</th>
                <th></th>
                </thead>
                <tbody>
                @foreach($rooms as $room)

                    <tr>
                        <td>{{$room->name_ar}}</td>
                        <td>{{$room->name_en}}</td>
                        <td>{{$room->size}}</td>
                        <td>
                            @if($room->approval == 0)
                                @lang('validation.attributes.no')
                                @else
                            @lang('validation.attributes.yes')
                                @endif
                        </td>
                        <td class="text-left">
                            <a class="btn btn-sm" href="{{ route('rooms.edit', $room->id) }}">@lang('validation.attributes.edit')</a>
                            <a class="btn btn-sm" href="{{ route('rooms.visit', $room->id) }}">@lang('validation.attributes.link')</a>
                            <button class="btn btn-sm btn-danger btn-delete" data-toggle="modal"
                                    data-target="#delete-modal-{{$room->id}}">@lang('validation.attributes.delete')</button>
                            <form method="post" action="{{ route('rooms.destroy', $room->id) }}">
                                <input type="hidden" name="_method" value="delete"/>
                                {{ csrf_field() }}
                                <!-- Modal HTML -->
                                <div id="delete-modal-{{$room->id}}" class="modal fade">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h4 class="modal-title">@lang('messages.delete_confirmation')</h4>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-default"
                                                        data-dismiss="modal">@lang('validation.attributes.no')</button>
                                                <button type="button" class="btn btn-primary"
                                                        onclick="$(this).closest('form').submit();">@lang('validation.attributes.yes')</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>


                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        @endif
    </div>
@endsection

resources/views/rooms/visits.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 user-scalable=0">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/bootstrap-rtl.min.css') }}">
    <link href="https://unpkg.com/ionicons@4.2.2/dist/css/ionicons.min.css" rel="stylesheet">
    <link href="{{ asset('css/room_visit_style.css') }}" rel="stylesheet">
</head>
<body>
<div class="header">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2 col-xs-2">
                <a class="navbar-brand" href="#">
                    @if(isset($settings->logo))
                        <img class="navbar-logo" src="{{ asset('/images/'.$settings->logo)}}"/>
                    @else
                        <img class="navbar-logo" src="{{ asset('/images/logo.png')}}"/>
                    @endif
                </a>
            </div>
            <div class="col-md-8 col-xs-8">
                <h1>
                    @if(app()->getLocale() == "ar")
                        {{$room->name_ar}}
                    @else
                        {{$room->name_en}}
                    @endif
                </h1>
            </div>
            <div class="col-md-2 col-xs-2">
                <a class="navbar-brand" href="#">
                    @if(isset($settings->logo))
                        <img class="navbar-logo" src="{{ asset('/images/'.$settings->logo)}}"/>
                    @else
                        <img class="navbar-logo" src="{{ asset('/images/logo.png')}}"/>
                    @endif
                </a>
            </div>
        </div>
    </div>
</div><!-- .header -->
<div class="container-fluid">
    <div class="row">
        <div class="col-md-7 col-sm-6">
            <table class="table" id="time-table">
                <thead>
                <tr>
                    <th><img id="meetings-logo" src="{{ asset('images/meetings_icon.png') }}">|
                        <span>الاجتماع</span>|
                        <span>Meeting</span>
                    </th>
                    <th>الوقت <span style="margin-right:10px;">|</span></th>
                    <th>Time</th>
                </tr>
                </thead>
                <tbody>
                @foreach($room->visits as $visit)
                    <tr>
                        <td class="col-md-3">{{$visit->title}}</td>
                        <td class="col-md-2">{{ date('g:i A', strtotime($visit->time_start)) }} <i class="icon ion-md-arrow-back" style="margin-right: 10px;"></i></td>
                        <td class="col-md-1">{{ date('g:i A', strtotime($visit->time_end)) }}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
         <div class="col-md-5 col-sm-6">
                <div class="current-meeting-label">
                    @if($currentMeeting != null)
                    <p id="now-paragraph"><span>الان</span><span>NOW</span></p>
                    <h1>{{$currentMeeting->title}}</h1>
                    <p id="start-finish-time-paragraph"><span>{{ date('g:i A', strtotime($currentMeeting->time_start)) }}</span><i class="icon ion-md-arrow-back"></i><span>{{ date('g:i A', strtotime($currentMeeting->time_end)) }}</span></p>
                    @else
                        <p>يمكنك حجز قاعة الاجتماعات هـذه عن طريق زيارة الرابط</p>
                        <p>You can book this meeting room by visiting the following link</p>
                        <h3>{{ env('APP_URL') }}</h3>
                    @endif
                </div>
            </div>
    </div>
</div>
<div class="current-date-label">
    Date | {{Date('Y-m-d')}}
</div>
<footer>
    <p>@lang('messages.screen_support')&nbsp;@if(isset($setting->support_mail)) {{ $setting->support_mail }} @endif</p>
</footer>
<script src="{{ asset('js/app.js') }}"></script>
<script>
    $(document).ready(function(){
        setInterval(function(){
            if(navigator.onLine){
                location.reload();
            }
        }, 10000);
    });
</script>
</body>
</html>